### ISSUE TITLE
Замечания по программе Replace

### ISSUE THREAD

**Issue by alexey-malov** [protasov-ilja/OOP#2]
https://github.com/protasov-ilja/OOP/blob/bdb575b3acc33891314177e17e88f748decf6486/lab1/lab1.1var4replace/lab1.1var4replace.cpp#L8

- [x] Не соблюдены соглашения о стиле кодирования
- [x] объекты следует передавать по константной **ссылке**, если функция не модифицирует их состояние.
Примитивные объекты передавать по константной ссылке выгоды нет, лучше по значению

**Comment by alexey-malov** [comment]
https://github.com/protasov-ilja/OOP/blob/bdb575b3acc33891314177e17e88f748decf6486/lab1/lab1.1var4replace/lab1.1var4replace.cpp#L10

- [ ] исправить опечатку

**Comment by alexey-malov** [comment]
- [ ] Выделить из main() код копирования содержимого файла с заменой

**Comment by alexey-malov** [comment]
https://github.com/protasov-ilja/OOP/blob/c3c65b23e2c24879a2170b0ff70b6e54dcf0c9ed/lab1/lab1.1var4replace/lab1.1var4replace.cpp#L60-L70
- [ ] Исправить, чтобы снизить сложность с O(N^2) до O(N)

**Comment by oMystique** [comment]
- [ ] Нет смысла передавать строку по значению в данном случае
```c++
string FindStringInLineAndReplace(string currString, ...
```

- [ ] Валятся тесты
```
1>------ Перестроение всех файлов начато: проект: lab1.1var4replace, Конфигурация: Debug x64 ------
1>stdafx.cpp
1>lab1.1var4replace.cpp
1>lab1.1var4replace.vcxproj -> E:\Teaching2018\Протасов Илья\OOP\lab1\x64\Debug\lab1.1var4replace.exe
1>Invalid arguments count
1>Usage: replace.exe <input file> <output file> <search string> <replace string>
1>Invalid arguments count
1>Usage: replace.exe <input file> <output file> <search string> <replace string>
1>Failed to open  for writing
1>Failed to open  for reading
1>You wrote empty searching string in argument #3
1>Invalid arguments count
1>Usage: replace.exe <input file> <output file> <search string> <replace string>
1>Сравнение файлов out.txt и OUTEMPTY.TXT
1>FC: различия не найдены
1>
1>Сравнение файлов out.txt и OUTSTRING-1-OR-MORE-REPLACE1.TXT
1>00000072: 0D 0A
1>FC: out.txt длиннее, чем OUTSTRING-1-OR-MORE-REPLACE1.TXT
1>
1>
1>Program testing failed :-(
1>E:\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: выход из команды "test.bat "E:\Teaching2018\Протасов Илья\OOP\lab1\x64\Debug\lab1.1var4replace.exe"
1>E:\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" с кодом 1.
1>Сборка проекта "lab1.1var4replace.vcxproj" завершена с ошибкой.
```

**Comment by alexey-malov** [comment]
- [ ] Выделить из main функцию, копирующую файл с заменой, которая бы принимала имена файлов

**Comment by alexey-malov** [comment]
Проблема с тестами, возможно, из-за настроек git-а, при которой вы коммитите файлы с другими символами конца строки
